### PR TITLE
Check for w-x backup directories

### PR DESCRIPTION
**Pull request by naptastic**
Case TECH-57: In CPANEL-4336, we determined that non-world-execute
directories in the path to the backup destination will cause .htaccess
files not to be modified correctly under some circumstances. Check
permissions and warn if any backup parent directories lack world-execute
permission.

### CODE REVIEW

**Comment by davelcpanelnet** [comment]
Please resubmit with updated SHA and version.

**Comment by naptastic** [comment]
Updated. I think I did it right?

**Comment by davelcpanelnet** [comment]
Looks great!

**Comment by cPanelChrisD** [comment]
The SHA512SUM value in the most recent commit doesn't actually match ssp, I've asked @naptastic for an update to SHA512SUM to address that.

There's also some extra white-space changes in unrelated code thanks to perltidy, but that is no big deal right now.  I think this may be a difference between the perltidy binary shipped with WHM 54 vs. 56 (or maybe dev sandbox vs. binary build) because he's using the same .perltidyrc that I am, yet the behavior is different.

**Comment by cPanelChrisD** [comment]
Also encountered this:
> Use of uninitialized value in split at ssp.nap line 3118.

`  3118      my @backup_path_parts = split( '/', $NEW_BACKUP_CONF->{BACKUPDIR} );`

This happens when backup.conf doesn't exist (such as on a fresh install, backups not configured).

**Comment by davelcpanelnet** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Ok.  I failed to check the Sha past seeing one there.

On March 17, 2016 2:52:26 PM CDT, cPanelChrisD <notifications@github.com> wrote:
>The SHA512SUM value in the most recent commit doesn't actually match
>ssp, I've asked @naptastic for an update to SHA512SUM to address that.
>
>There's also some extra white-space changes in unrelated code thanks to
>perltidy, but that is no big deal right now.  I think this may be a
>difference between the perltidy binary shipped with WHM 54 vs. 56 (or
>maybe dev sandbox vs. binary build) because he's using the same
>.perltidyrc that I am, yet the behavior is different.
>
>
>---
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/cPanelSSP/SSP/pull/77#issuecomment-198055930

- --
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQE9BAEBCgAnBQJW6wzDIBxEYXZlIExhbm5pbmcgPGRhdmVsQGNwYW5lbC5uZXQ+
AAoJEOnT2p1m+tjgf4kIALH4wMWe2EKgdt6IHmAkiDu4aa0EcmyXu6moQf6tpcE3
qfHNAmaW9Cv/Uw3FSPOKP2bvRPNtS3hZnjLj/QSHFV8b+oudjwpwzfxlgpsU0D3S
eY7JL/e7C37duN7PnbhIj80uFJQM7wCJa/yJ6BdtZEgvPlVshAf21yMgmLA7vbMe
pQWuyBcEOBl7q5OORTG7Q0EyhZ4ZNNDv824xOq2sBxZxutZd9PqH9TE/ROLr17lW
/DI29+0r40zHaM69zSktYEQFLvgw7+8rEFP7wAi9gofzk4volW/KDnr7Dm6DBgZ8
xvE3d3bUXYpVgl++vXEmW3NpIdCDukVFsWqdDzrKfxU=
=h0aK
-----END PGP SIGNATURE-----

**Pull request merged**
