### PR TITLE
Update bugreport template to accommodate the new JIRA template.

### PR DESCRIPTION
**Pull request by cPanelPeter**
Changed the template for --bugreport option to accommodate the new JIRA template. Per Jesse Asklund

### CODE REVIEW

**Comment by davelcpanelnet** [comment]
Looks good.

Reviewed: davelcpanelnet Fri Jul 10 11:47:54 CDT 2015

**Comment by cPanelPeter** [comment]
Hi Dave,

Thanks.  I just checked and the version number didn't update (I had 
updated it) and testing this, it's still showing the old bugreport 
template.

Did I miss something?

Thanks,
Peter

**Comment by cborsheim** [comment]
Ssp.cpanel.net doesn't automatically pull from github. Only those with
access to ssp.cpanel.net can make the pull to the server.

**Comment by davelcpanelnet** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Did we update the Sha?

On July 10, 2015 4:19:29 PM CDT, Peter Elsner <notifications@github.com> wrote:
>Hi Dave,
>
>Thanks.  I just checked and the version number didn't update (I had
>updated it) and testing this, it's still showing the old bugreport
>template.
>
>Did I miss something?
>
>Thanks,
>Peter
>
>
>On 07/10/2015 11:48 AM, David Lanning wrote:
>>
>> Merged #48 <https://github.com/cPanelSSP/SSP/pull/48>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cPanelSSP/SSP/pull/48#event-353106874>.
>>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cPanelSSP/SSP/pull/48#issuecomment-120532027

- --
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQE9BAEBCgAnBQJVoDpyIBxEYXZlIExhbm5pbmcgPGRhdmVsQGNwYW5lbC5uZXQ+
AAoJEOnT2p1m+tjgba0IAJH5IRAGuIbGvtjVC6lbtYKZF8rLNIMjUdDrXLXSlP7u
p9D10TsNYk90a394W1hEP12Lw3de/Wbgzcx1An5+PYFo834OD2h+XAYg4TJ9+dSN
rnFpmAalniTkOnXzF3dDPauQwzithfaw8oW8KYvW07+jqGiHQUd4YyMnPmJERJ87
qZiwb9K5/0/9oaMbSfIpNStNO8kdri7YgXyggCsCKBilGjHV/QXS01qGfj+FQYC+
8uwkTIZbEjSwVmnS9Use4WfQ+U/iXDIkms0nNqBju80idMLKs7UUwqVdb178Y69t
fxdBzlF53Urs8EDiP59cJ6zVvqzrM9w5kjQiy2SnPQ0=
=9bli
-----END PGP SIGNATURE-----

**Comment by cPanelPeter** [comment]
Ah no I didn't.  What is the command for that?  





On July 10, 2015 4:34:50 PM CDT, David Lanning <notifications@github.com> wrote:
>-----BEGIN PGP SIGNED MESSAGE-----
>Hash: SHA512
>
>Did we update the Sha?
>
>On July 10, 2015 4:19:29 PM CDT, Peter Elsner
><notifications@github.com> wrote:
>>Hi Dave,
>>
>>Thanks.  I just checked and the version number didn't update (I had
>>updated it) and testing this, it's still showing the old bugreport
>>template.
>>
>>Did I miss something?
>>
>>Thanks,
>>Peter
>>
>>
>>On 07/10/2015 11:48 AM, David Lanning wrote:
>>>
>>> Merged #48 <https://github.com/cPanelSSP/SSP/pull/48>.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/cPanelSSP/SSP/pull/48#event-353106874>.
>>>
>>
>>
>>
>>---
>>Reply to this email directly or view it on GitHub:
>>https://github.com/cPanelSSP/SSP/pull/48#issuecomment-120532027
>
>- --
>Sent from my Android device with K-9 Mail. Please excuse my brevity.
>-----BEGIN PGP SIGNATURE-----
>Version: APG v1.1.1
>
>iQE9BAEBCgAnBQJVoDpyIBxEYXZlIExhbm5pbmcgPGRhdmVsQGNwYW5lbC5uZXQ+
>AAoJEOnT2p1m+tjgba0IAJH5IRAGuIbGvtjVC6lbtYKZF8rLNIMjUdDrXLXSlP7u
>p9D10TsNYk90a394W1hEP12Lw3de/Wbgzcx1An5+PYFo834OD2h+XAYg4TJ9+dSN
>rnFpmAalniTkOnXzF3dDPauQwzithfaw8oW8KYvW07+jqGiHQUd4YyMnPmJERJ87
>qZiwb9K5/0/9oaMbSfIpNStNO8kdri7YgXyggCsCKBilGjHV/QXS01qGfj+FQYC+
>8uwkTIZbEjSwVmnS9Use4WfQ+U/iXDIkms0nNqBju80idMLKs7UUwqVdb178Y69t
>fxdBzlF53Urs8EDiP59cJ6zVvqzrM9w5kjQiy2SnPQ0=
>=9bli
>-----END PGP SIGNATURE-----
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/cPanelSSP/SSP/pull/48#issuecomment-120534968

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cborsheim** [comment]
There is no command, it requires access to the server itself. Dillon and
myself only have access. I emailed Jesse about it so he can get access and
do the fetch request when he gets to the office.

**Pull request merged**
