### PR TITLE
Detect Memory Below Requirements

### PR DESCRIPTION
**Pull request by cPPietila**
Currently, SSP detects if the memory is below 512 MB ram. However, cPanel requires a bit more, as documented in https://documentation.cpanel.net/display/ALD/Installation+Guide+-+Hardware+Requirements and https://documentation.cpanel.net/display/ALD/Installation+Guide+-+Configuration . This pull request resolves those differences.

### CODE REVIEW

**Comment by cPanelChrisD** [comment]
There are a few things that would need to be addressed, other than the lack of a version number bump and SHA512SUM update which would also be required for a successful merge of a pull request:

1) Unnecessary opening and parsing of /etc/redhat-release.  We have existing mechanisms available that will allow you to check the OS release in far fewer lines of code.  Examples are available in many other checks, but basically all you need is:

if ( version_compare($os_release, qw( < 7 ) ) { do_stuff; }

2) You can't use single-quotes around interpolated strings, or you're going to see the variable name in the output instead of what you expected, which leads me to believe that this wasn't actually tested.

print_warning('Server has less than recommended swap memory. [$totalswap MB]');

Will print that string verbatim, and $totalswap will not be interpolated.  You must use double-quotes when interpolating variables inside of a string, or else it must be broken into multiple concatenated strings and then you could continue to use single-quotes:

print_warning('Server has less than recommended swap memory. [' . $totalswap . ' MB]');

3) While using swap is not actually discouraged, we do not require or actually recommend any amount of it in our hardware requirements documentation, because it should not be relied upon.  Even if we were to recommend an amount of swap space, the reasoning behind the various numbers being chosen for the recommended swap sizing are not clear, and there's multiple uses of the same "magic numbers" which could be converted into constants (not literal perl constants, but at least assigned to an appropriately-named variable before usage in multiple locations).

**Comment by cPPietila** [comment]
1. Ok, I didn't actually see that faculty. I've modified the code to reflect that suggestion.

2. That's what I get for coding late at night. I've corrected it and tested it with a big value for $one_gigabyte_roughly, so that should be correct now.

3a. I do stand by my wording for "recommended", as that's what the wording is in the Installation guide itself. I removed the check for $softrecommendedswap as I've never had an issue with a client not following that guide, mostly that they have no swap or far too little.

3b. I've moved the magic gigabyte to $one_gigabyte_roughly

**Comment by cPPietila** [comment]
Updated to current head.

**Comment by davelcpanelnet** [comment]
Hello, cPPietila, and thank you for your pull request and taking interest in contributing to SSP.

1) The matters that were brought up by PanelChrisD are definitely valid concerning swap.  I would hate to display any information about swap whatsoever as so many machines do allocate memory to the point of being within swap:

Example:

root@centos6 [~]# free -m
             total       used       free     shared    buffers     cached
Mem:           996        889        107          0        138        407
-/+ buffers/cache:        343        653
Swap:         2015         45       1970

This is a virtualbox vm hitting swap without any complications on a deployed server. 

This said having SWAP information displayed would generate a signal / noise ratio that may only serve to clutter the output from SSP as a whole.

2) The memory limits coming down the pipe for 11.52 roll back.  The future documentation cites a requirement of only 768MB ( due to memory trimming done in 11.52 ) regardless of CentOS or Cloudlinux. 

These things said the code looks really good.  If you can resubmit with the following done I would be happy to merge:

a) Unplug the swap notifications.
b) Change the requirements from 1024 to 768 as this will be more in line with future releases.

You could also get version specific and warn on 1024 in 11.50 or lower and 768 in 11.52 and higher.  This would adhere more to the product and serve to future proof for the upcoming 11.52 release.

**Pull request closed without merging**
