### PR TITLE
Fix corner case OpenVZ memory detection.

### PR DESCRIPTION
**Pull request by cPPietila**
[WARN] * Memory: Server has less than 768MB installed memory! [ 0MB ]
[WARN] * Memory: Server has less than 1024MB swap! [ unknown ]

### CODE REVIEW

**Comment by cPanelChrisD** [comment]
Without seeing the /proc/user_beancounters that resulted in the warning, I'm very hesitant to say that the logic changes here are sound.  I've recently come across another server where this happened and I have a copy of /proc/user_beancounters from it, so I will see if this works, or if a different fix is necessary in that case.

**Comment by cPanelChrisD** [comment]
It does look like it was the same issue, and I believe this is now fixed via TECH-89, which also simplified the code a little bit.  The fix was similar, to ignore a value of zero.

**Comment by cPanelChrisD** [comment]
Because this is fixed via TECH-89, I suggest closing this pull request.

**Comment by davelcpanelnet** [comment]
Closing this out as a duplicate.

**Pull request closed without merging**
