### PR TITLE
Add check for Linux OOM Killer

### PR DESCRIPTION
**Pull request by cPPietila**
Multiple tickets recently have shown issues with Linux's OOM killer killing processes, such as MySQL. This changeset makes it so that SSP can adequately check for such slayings.

Code was mostly borrowed from the LFD and PRM relatives. Sample output:

[WARN] * Last 3 processes killed by Linux Out of memory killer (grep "Out of memory" /var/log/messages):
	 \_ [Sep  3 02:14:27] [pid: 1750] [cmd: mysqld] [vm: 456120 kB] [rss: 410876 kB] [swap: 0 kB]
	 \_ [Sep  3 02:14:26] [pid: 1689] [cmd: mysqld] [vm: 3168032 kB] [rss: 432076 kB] [swap: 0 kB]
	 \_ [Sep  3 02:14:23] [pid: 303] [cmd: mysqld] [vm: 3435600 kB] [rss: 481652 kB] [swap: 264 kB]

### CODE REVIEW

**Comment by cborsheim** [comment]
Andrew,

We do not use code from other software companies without written
permission. From CSF's licensing agreement for their script license (
http://download.configserver.com/csf/license.txt):

.	SCOPE OF LICENCE

	3.1	You shall not:

		3.1.1	modify, adapt, merge, translate, decompile,
		disassemble, or reverse engineer the Product, except as
		permitted by law; or

		3.1.2	sell, assign, rent, sub-license, loan, mortgage,
		charge or otherwise deal in any way in the Product or
		Documentation or any interest in them except as expressly
		provided in this Licence.


Please re-write, and resubmit original code. Thanks!

**Comment by bdraco** [comment]
Please use  Cpanel::Sys::OOM instead as we already have a module for this

**Comment by cborsheim** [comment]
Andrew,

Did you mean you borrowed the code from SSP's subroutines for checking LFD
& RPM, and not that the code was borrowed from CSF?

check_for_processes_killed_by_lfd();
check_for_processes_killed_by_prm();

The commit message reads as though the code was found in a third party
product, rather than cPanel owned code. Could you clarify a bit? Thanks :)

**Comment by cPanelChrisD** [comment]
It appears that Andrew specifically meant borrowing from the existing LFD/PRM checks in SSP itself, not from third-party code.  The check is nearly identical to our pre-existing checks but modified minimally to check for OOM Killer events in /var/log/messages, and I heartily approve of that kind of internal code-borrowing.  Though when when we start copy/pasting existing SSP functions and only make a few specific changes it makes me want to refactor all of them into a single check that handles All The Things, like I've already done for most of the separate file/directory permission checks.  That level of refactoring can probably wait for another day, though.

Regarding the use of Cpanel::Sys::OOM, this is a module that is apparently not available on anything less than WHM 11.52 so cannot be relied upon to exist externally on the older systems that SSP runs on.  Although SSP could be packed with external modules like Cpanel::Sys::OOM, I believe SSP should continue to exist as a monolithic script for as long as we are still able to maintain it as such, and avoid using any module-packing methods that would require the use of tmp space (such as ppk-bundle).  Fairly often /tmp is completely full, and SSP wouldn't execute at all if it has to be temporarily "unpacked", so it would reduce its utility in those situations.  Any module-packing methods that don't require tmp space would preserve that functionality, though, so that may be an option?

**Comment by bdraco** [comment]
You could use /usr/local/cpanel/bin/perlpkg in 11.52

**Comment by cPPietila** [comment]
> Did you mean you borrowed the code from SSP's subroutines for checking LFD & RPM, and not that the code was borrowed from CSF?

Yeah... sorry for the ambiguity... I thought based on positioning and structure that it was clear. I'll resubmit with an amended commit message.

**Pull request closed without merging**
